/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhir;

import com.User;
import com.Admin;

import com.ConverterUser;
import com.ConverterSepatu;
import com.Sepatu;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author User
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        setdataUser();
        setdataSepatu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setdataUser(){
        ConverterUser convUs = new ConverterUser();
        String[][] datauser = convUs.getUser();
        tblUserAdmin.setModel(new javax.swing.table.DefaultTableModel(
        
        datauser,
           new String []{
          "ID", "Nama", "Email", "Notelp", "Username","Password"      
           }
        ));
        jScrollPane2.setViewportView(tblUserAdmin);
    }
    
    private void setdataSepatu(){
        ConverterSepatu conv = new ConverterSepatu();
        String[][] dataSepatu = conv.getSepatu();
        tblsptuAdmin.setModel(new javax.swing.table.DefaultTableModel(
        
        dataSepatu,
           new String []{
          "ID Sepatu", "Nama", "Harga"      
           }
        ));
        jScrollPane1.setViewportView(tblsptuAdmin);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnuser = new javax.swing.JButton();
        isi = new javax.swing.JPanel();
        pnlMngUser = new javax.swing.JPanel();
        btnCreate1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUserAdmin = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNamaUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        txtUnUser = new javax.swing.JTextField();
        txtPwUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlMngSpt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsptuAdmin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJHargaa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(39, 102, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/small.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 80, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/icons8_logout_32px.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 60, 50));

        btnuser.setBackground(new java.awt.Color(255, 255, 255));
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/icons8_user_settings_32px.png"))); // NOI18N
        btnuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnuserMouseClicked(evt);
            }
        });

        isi.setLayout(new java.awt.CardLayout());

        pnlMngUser.setBackground(new java.awt.Color(39, 102, 168));

        btnCreate1.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate1.setForeground(new java.awt.Color(0, 0, 0));
        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        btnUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete1.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        tblUserAdmin.setBackground(new java.awt.Color(255, 255, 255));
        tblUserAdmin.setBorder(null);
        tblUserAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUserAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUserAdmin);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Data User");

        jLabel6.setText("ID");

        txtIDUser.setBackground(new java.awt.Color(255, 255, 255));
        txtIDUser.setForeground(new java.awt.Color(0, 0, 0));
        txtIDUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUserActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama");

        txtNamaUser.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaUser.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setText("Email");

        txtEmailUser.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailUser.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUserActionPerformed(evt);
            }
        });

        txtNotelp.setBackground(new java.awt.Color(255, 255, 255));
        txtNotelp.setForeground(new java.awt.Color(0, 0, 0));
        txtNotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotelpActionPerformed(evt);
            }
        });

        txtUnUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUnUser.setForeground(new java.awt.Color(0, 0, 0));

        txtPwUser.setBackground(new java.awt.Color(255, 255, 255));
        txtPwUser.setForeground(new java.awt.Color(0, 0, 0));
        txtPwUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwUserActionPerformed(evt);
            }
        });

        jLabel9.setText("No. Telp");

        jLabel10.setText("Username");

        jLabel11.setText("Password");

        javax.swing.GroupLayout pnlMngUserLayout = new javax.swing.GroupLayout(pnlMngUser);
        pnlMngUser.setLayout(pnlMngUserLayout);
        pnlMngUserLayout.setHorizontalGroup(
            pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMngUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMngUserLayout.createSequentialGroup()
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMngUserLayout.createSequentialGroup()
                                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(64, 64, 64)
                                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlMngUserLayout.createSequentialGroup()
                                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(43, 43, 43)
                                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPwUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngUserLayout.createSequentialGroup()
                                .addComponent(btnCreate1)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate1)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete1)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngUserLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(304, 304, 304))))))
        );
        pnlMngUserLayout.setVerticalGroup(
            pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMngUserLayout.createSequentialGroup()
                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMngUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMngUserLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPwUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlMngUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1)
                    .addComponent(btnDelete1)
                    .addComponent(btnCreate1))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        isi.add(pnlMngUser, "cardMngUser");

        pnlMngSpt.setBackground(new java.awt.Color(39, 102, 168));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblsptuAdmin.setBackground(new java.awt.Color(255, 255, 255));
        tblsptuAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsptuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsptuAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsptuAdmin);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage Data Sepatu");

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Sepatu");

        jLabel13.setText("Nama");

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setForeground(new java.awt.Color(0, 0, 0));

        txtJHargaa.setBackground(new java.awt.Color(255, 255, 255));
        txtJHargaa.setForeground(new java.awt.Color(0, 0, 0));
        txtJHargaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJHargaaActionPerformed(evt);
            }
        });

        jLabel14.setText("Harga");

        javax.swing.GroupLayout pnlMngSptLayout = new javax.swing.GroupLayout(pnlMngSpt);
        pnlMngSpt.setLayout(pnlMngSptLayout);
        pnlMngSptLayout.setHorizontalGroup(
            pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMngSptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMngSptLayout.createSequentialGroup()
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(64, 64, 64)
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJHargaa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngSptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngSptLayout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMngSptLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(299, 299, 299))))))
        );
        pnlMngSptLayout.setVerticalGroup(
            pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMngSptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMngSptLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMngSptLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJHargaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlMngSptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCreate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        isi.add(pnlMngSpt, "cardMngKue");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User Data");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/icons8_sneakers_32px.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("    Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private CardLayout clAD;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda Keluar dari Admin Sistem!");
        this.dispose();
        loginn log = new loginn();
        log.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
        String id = txtIDUser.getText();
        String nama = txtNamaUser.getText();
        String email = txtEmailUser.getText();
        String notelp = txtNotelp.getText();
        String username = txtUnUser.getText();
        String password = txtPwUser.getText();
        
        //Mmasukkan pngguna bru k database
        User user = new User(id, nama, email, notelp, username, password);
        Execute.ExecuteUsers EUser = new Execute.ExecuteUsers();
        int hasil = EUser.insertUser(user);
        if (hasil>0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataUser();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal menyimpan");
        }
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        String id_user = txtIDUser.getText();
        String nama_user = txtNamaUser.getText();
        String email_user = txtEmailUser.getText();
        String notelp_user = txtNotelp.getText();
        String un_user = txtUnUser.getText();
        String pws_user = txtPwUser.getText();

        User user = new User(id_user, nama_user, email_user, notelp_user, un_user, pws_user);
        Execute.ExecuteUsers eUsers = new Execute.ExecuteUsers();
        int hasil = eUsers.updateUser(user);
        if (hasil>0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setdataUser();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal mengubah");
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        String id_user = txtIDUser.getText();
        Execute.ExecuteUsers eUser = new Execute.ExecuteUsers();
        int hasil = eUser.deleteUser(id_user);
        if (hasil > 0){
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            setdataUser();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal menghapus");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void tblUserAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserAdminMouseClicked
        // TODO add your handling code here:
        int row = tblUserAdmin.getSelectedRow();
        String id = tblUserAdmin.getValueAt(row, 0).toString();
        String nama = tblUserAdmin.getValueAt(row, 1).toString();
        String email = tblUserAdmin.getValueAt(row, 2).toString();
        String notelp = tblUserAdmin.getValueAt(row, 3).toString();
        String username = tblUserAdmin.getValueAt(row, 4).toString();
        String password = tblUserAdmin.getValueAt(row, 5).toString();
        txtIDUser.setText(id);
        txtNamaUser.setText(nama);
        txtEmailUser.setText(email);
        txtNotelp.setText(notelp);
        txtUnUser.setText(username);
        txtPwUser.setText(password);
    }//GEN-LAST:event_tblUserAdminMouseClicked

    private void txtIDUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUserActionPerformed

    private void txtEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUserActionPerformed

    private void txtNotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotelpActionPerformed

    private void txtPwUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwUserActionPerformed

    private void btnuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMouseClicked
        // TODO add your handling code here:
        clAD = (CardLayout) isi.getLayout();
        clAD.show(isi, "cardMngUser");
    }//GEN-LAST:event_btnuserMouseClicked

    private void tblsptuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsptuAdminMouseClicked
        // TODO add your handling code here:
        int row = tblsptuAdmin.getSelectedRow();
        String id = tblsptuAdmin.getValueAt(row, 0).toString();
        String nama = tblsptuAdmin.getValueAt(row, 1).toString();
        String harga = tblsptuAdmin.getValueAt(row, 2).toString();
        txtID.setText(id);
        txtNama.setText(nama);
        txtJHargaa.setText(harga);
    }//GEN-LAST:event_tblsptuAdminMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String id_sepatu = txtID.getText();
        String nama_sepatu = txtNama.getText();
        String strHarga = txtJHargaa.getText();
        int harga_sepatu = Integer.parseInt(strHarga);

        Sepatu spt = new Sepatu(id_sepatu, nama_sepatu, harga_sepatu);
        Execute.ExecuteSepatu eSptu = new Execute.ExecuteSepatu();
        int hasil = eSptu.createSepatu(spt);
        if (hasil>0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataSepatu();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal menyimpan");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id_sepatu = txtID.getText();
        String nama_sepatu = txtNama.getText();
        String strHarga = txtJHargaa.getText();
        int harga_sepatu = Integer.parseInt(strHarga);

        Sepatu spt = new Sepatu(id_sepatu, nama_sepatu, harga_sepatu);
        Execute.ExecuteSepatu eSpt = new Execute.ExecuteSepatu();
        int hasil = eSpt.updateSepatu(spt);
        if (hasil>0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setdataSepatu();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal mengubah");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id_sepatu = txtID.getText();
        Execute.ExecuteSepatu eSpt = new Execute.ExecuteSepatu();
        int hasil = eSpt.deleteSepatu(id_sepatu);
        if (hasil > 0){
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            setdataSepatu();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal menghapus");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtJHargaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJHargaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJHargaaActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        pnlMngSpt.setVisible(true);
        pnlMngUser.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnuser;
    private javax.swing.JPanel isi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlMngSpt;
    private javax.swing.JPanel pnlMngUser;
    private javax.swing.JTable tblUserAdmin;
    private javax.swing.JTable tblsptuAdmin;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDUser;
    private javax.swing.JTextField txtJHargaa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtPwUser;
    private javax.swing.JTextField txtUnUser;
    // End of variables declaration//GEN-END:variables

    private void setColor(JButton btnuser) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
